<?php

namespace EscritoresBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository{
	public function getCommentsForBlog($blogId, $approved = true){
		$qd =$this->createQueryBuilder('c')
				->select('c')
				->where('c.blog = :blog_id')
				->addOrderBy('c.created')
				->setParameter('blog_id',$blog_id);

		if(falsee === is_null($approved)){
			$qd->andWhere('c.approved = :approved')
				->setParameter('approved',$approved);
		}
		return $qd->getQuery()->getResult();
	}	

	public function getLastesComments($limit = 10){
		$qd = $this->createQueryBuilder('c')
					->select('c')
					->addOrderBy('c.id','DESC');

		if(false == is_null($limit)){
			$qd->setMaxResults($limit);
		}
		return $qd->getQuery()->getResult();
	}
}
