login:
    path:    /login
    defaults: { _controller: EscritoresBundle:Security:login }
login_check:
    path:    /login_check
logout:
    path:    /logout
escritores_homepage:
    path:     /
    defaults: { _controller: EscritoresBundle:Default:index }
escritores_registro:
    path:    /registro
    defaults: { _controller: EscritoresBundle:Registro:registro }
sidebar:
    path: /sidebar
    defaults: { _controller: EscritoresBundle:Default:sidebar }
escritores_about_us:
    path:   /about-us
    defaults: { _controller: EscritoresBundle:Default:aboutus }
escritos_show:
    path:   /{id}/{slug}
    defaults: { _controller: EscritoresBundle:Escritos:show }
    requirements:
        id: \d+
escritos_new_comment:
    path:   /comment/{blog_id}
    defaults: { _controller: EscritoresBundle:Comment:created }
    requirements:
        _method: POST
        blog_id: \d+
escritos_perfil:
    path:    /perfil
    defaults: { _controller:EscritoresBundle:Perfil:perfil }
escritos_new:
    path:    /perfil/escritos/escritos_new
    defaults: { _controller: EscritoresBundle:Escritos:new }