services:
#    escritores.example:
#        class: EscritoresBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    blogger_blog_extension:
        class: EscritoresBundle\Twig\Extensions\EscritoresExtension
        tags:
            - { name: twig.extension }